using Mutagen.Bethesda;
using Mutagen.Bethesda.Json;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using Noggog;
using System.Data;
using System.Diagnostics;
using System.IO.Compression;
using System.Text;
using System.Text.RegularExpressions;

namespace SynPatcher;

public static class Program
{
    public static IEnumerable<(HashSet<string>, string)> GenerateTemplatedCartesianProduct(
        this Dictionary<string, HashSet<string>> data,
        string template)
    {
        // Start with a single empty dictionary to represent the initial state
        IEnumerable<Dictionary<string, string>> combinations = [[]];

        // Iterate through each key-value pair in the input dictionary
        foreach (var entry in data)
        {
            // For each existing combination, create new combinations by adding each value from the current list
            combinations = combinations.SelectMany(
                existingCombination => entry.Value.Select(
                    value =>
                    {
                        var newCombination = new Dictionary<string, string>(existingCombination);
                        newCombination[entry.Key] = value;
                        return newCombination;
                    }));
        }

        // Now, format each generated combination into the template string
        foreach (var combination in combinations)
        {
            HashSet<string> vals = [];
            string formattedString = template;
            foreach (var kvp in combination)
            {
                // Replace placeholders in the template with the corresponding values
                vals.Add(kvp.Value);
                formattedString = formattedString.Replace($"<{kvp.Key}>", kvp.Value);
            }
            yield return (vals, formattedString);
        }
    }
    public static async Task DownloadFileAsync(string fileUrl, string destinationPath)
    {
        try
        {
            HttpClient dlclient = new();
            using var fileStream = new FileStream(destinationPath, FileMode.Create, FileAccess.Write, FileShare.None);
            var resp = await dlclient.GetStreamAsync(fileUrl);
            await resp.CopyToAsync(fileStream);
            Log($"Downloaded: {destinationPath}", LogMode.NORMAL);
        }
        catch (HttpRequestException ex)
        {
            Log($"HTTP error: {ex.Message}", LogMode.NORMAL);
        }
        catch (IOException ex)
        {
            Log($"File I/O error: {ex.Message}", LogMode.NORMAL);
        }
    }
    static Dictionary<string, LineTracker> lines = [];
    static Lazy<APIConfig> api = new();
    public static APIConfig APIInfo => api.Value;
    static readonly HttpClient client = new();
    static string EDFP = string.Empty;
    static string mp3 = string.Empty;
    static string wav = string.Empty;
    static string lip = string.Empty;
    static string xwm = string.Empty;
    static string fuz = string.Empty;
    static string CKTools = string.Empty;
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance.SetAutogeneratedSettings("API Config", "SynVG.json", out api).SetTypicalOpen(GameRelease.SkyrimSE, "Labs.esp").AddPatch<ISkyrimMod, ISkyrimModGetter>(Patch).Run(args);
    }
    static bool IsValidChar(char x) => Char.IsAsciiLetterOrDigit(x) || x == '-' || x == '=' || x == '$' || x == '<' || x == '>' || x == ' ' || x == '.' || x == ',' || x == '?' || x == '!' || x == '\"' || x == '\'' || x == '*' || x == '[' || x == ']' || x == '(' || x == ')';
    static string CleanString(string str) => new string([.. REG.HiddenFN2.Replace(REG.HiddenFN.Replace(str, ""), "").Where(IsValidChar)]).Trim().TrimEnd('.').TrimEnd('!').TrimEnd(',').TrimEnd('?').Replace("\n", " ").Replace("\r", " ").Replace("\t", " ").Replace("  ", " ").TrimEnd(' ');
    static void Patch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        JsonSerializerSettings settings = new();
        settings.AddMutagenConverters();
        settings.Formatting = Formatting.Indented;
        EDFP = state.ExtraSettingsDataPath ?? string.Empty;
        var parent = Directory.GetParent(state.DataFolderPath);
        CKTools = Path.Join(parent?.FullName, "Tools");
        Directory.CreateDirectory(Path.Join(state.ExtraSettingsDataPath, "tmp"));
        if (!File.Exists(Path.Join(state.ExtraSettingsDataPath, "ffmpeg.exe")))
        {
            if (!File.Exists(Path.Join(state.ExtraSettingsDataPath, "tmp", "FFMPEG.zip")))
            {
                DownloadFileAsync("https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n8.1-latest-win64-gpl-8.1.zip", Path.Join(state.ExtraSettingsDataPath, "tmp", "FFMPEG.zip")).Wait();
                using var zip = ZipFile.OpenRead(Path.Join(state.ExtraSettingsDataPath, "tmp", "FFMPEG.zip"));
                var ent = zip.Entries.Where(x => x.Name == "ffmpeg.exe").First();
                ent.ExtractToFile(Path.Join(state.ExtraSettingsDataPath, "ffmpeg.exe"));
            }
        }
        if (!File.Exists(Path.Join(state.ExtraSettingsDataPath, "FaceFXWrapper.exe")))
        {
            DownloadFileAsync("https://github.com/Nukem9/FaceFXWrapper/releases/download/0.41/FaceFXWrapper.0.41.zip", Path.Join(state.ExtraSettingsDataPath, "tmp", "facefx.zip")).Wait();
            using var zip = ZipFile.OpenRead(Path.Join(state.ExtraSettingsDataPath, "tmp", "facefx.zip"));
            var ffxw = zip.Entries.Where(x => x.Name == "FaceFXWrapper.exe").First();
            ffxw.ExtractToFile(Path.Join(state.ExtraSettingsDataPath, "FaceFXWrapper.exe"));
        }
        if (!File.Exists("FonixData.cdf"))
        {
            File.Copy(Path.Join(CKTools, "LipGen", "LipGenerator", "FonixData.cdf"), "FonixData.cdf");
        }

        var voice_directory = Path.Join(state.DataFolderPath, "Sound", "VPC", "DefaultVoice");
        var voice_sound = Path.Join(voice_directory, "Voice");
        var voice_data = Path.Join(voice_directory, "Data");
        if (Directory.Exists(voice_data))
        {
            foreach (var dir in Directory.EnumerateDirectories(voice_data))
            {
                var fn = new DirectoryInfo(dir).Name;
                Log($"Loading files for {fn}", LogMode.NORMAL);
                if (!state.LoadOrder.ModExists(fn)) continue;
                foreach (var file in Directory.EnumerateFiles(dir))
                {
                    if (file.EndsWith(".json"))
                    {
                        var form = Path.GetFileNameWithoutExtension(file);
                        var fk = FormKey.Factory($"{form}:{fn}");
                        if (state.LinkCache.TryResolve<IDialogTopicGetter>(fk, out var vt))
                        {
                            var n = CleanString($"{vt.Name}");
                            if (n.IsNullOrEmpty()) continue;
                            Log($"Loading entry for {fk}: {CleanString($"{vt.Name}")}", LogMode.DEBUG);
                            if (lines.TryGetValue(n, out LineTracker? lin))
                            {
                                var varint = JsonConvert.DeserializeObject<HashSet<VariantData>>(File.ReadAllText(file), settings)!;
                                Log($"Merging {lin.forms.First()} with {lin.variants.Count} variants with {fk} containing text {CleanString($"{vt.Name}")} and {varint.Count} variants", LogMode.DEBUG);
                                lin.forms.Add(fk);
                                lin.variants.Add(varint);
                                lin.variants = lin.variants.DistinctBy(x => x.guid).ToHashSet();
                                Log($"Final Variant Count {lin.variants.Count}", LogMode.DEBUG);
                            }
                            else
                            {
                                var lt = new LineTracker();
                                lt.forms.Add(fk);
                                lt.variants = JsonConvert.DeserializeObject<HashSet<VariantData>>(File.ReadAllText(file), settings)!;
                                if (lt.variants.Count > 0)
                                {
                                    lines[n] = lt;
                                }
                            }
                        }
                    }
                }
            }
        }
        var vgroot = Path.Join(EDFP, "VGOutput");
        mp3 = Path.Join(vgroot, "mp3");
        wav = Path.Join(vgroot, "wav");
        lip = Path.Join(vgroot, "lip");
        xwm = Path.Join(vgroot, "xwm");
        fuz = Path.Join(vgroot, "fuz");
        Directory.CreateDirectory(mp3);
        Directory.CreateDirectory(wav);
        Directory.CreateDirectory(lip);
        Directory.CreateDirectory(xwm);
        Directory.CreateDirectory(fuz);
        client.BaseAddress = new Uri(APIInfo.api_server);
        client.Timeout = TimeSpan.FromMinutes(5);
        foreach (var (Name, FormKey, Responses) in state.LoadOrder.PriorityOrder.DialogTopic().WinningOverrides().Where(x => $"{x.Name}" != x.EditorID && x.Category == DialogTopic.CategoryEnum.Topic).Where(x => !$"{CleanString($"{x.Name}")}".IsNullOrEmpty() && $"{x.Name}" != $"{x.EditorID}").Select(x => (CleanString($"{x.Name}"), x.FormKey, x.Responses)))
        {
            try
            {
                var line = ProcLine(Name, FormKey);
                if (line == null) continue;
                if (line.variants.Count == 0) continue;
                if (Responses.Any(x => x.Prompt != null))
                {
                    var cs = Responses.Where(x => x.Prompt != null && !x.Prompt.ToString().IsNullOrEmpty()).Select(x => (x.Prompt!.ToString()!, CleanString(x.Prompt!.ToString()!)));
                    Log($"Generating ${cs.Count()} prompts", LogMode.NORMAL);
                    foreach (var c in cs)
                    {
                        LineData? newvint = Generate(c.Item2);
                        if (newvint != null)
                        {
                            line.variants.Add(new VariantData
                            {
                                guid = newvint.Value.guid,
                                splen = newvint.Value.splen,
                                reg_frags = c.Item1.Split(' ').Except(Name.Split(' ')).ToHashSet(),
                            });
                        }
                    }
                    Log($"Generated Prompts", LogMode.NORMAL);
                }
                if (!Directory.Exists(Path.Join(voice_data, FormKey.ModKey.ToString())))
                    Directory.CreateDirectory(Path.Join(voice_data, FormKey.ModKey.ToString()));
                foreach (var vd in line.variants)
                {
                    var fp = Path.Join(voice_sound, $"{vd.guid}.fuz");
                    var ep = Path.Join(state.ExtraSettingsDataPath, "VGOutput", "fuz", $"{vd.guid}.fuz");
                    if (!File.Exists(ep))
                    {
                        File.Copy(fp, ep);
                    }
                }
                foreach (var vint in line.forms)
                {
                    var jso = Path.Join(voice_data, vint.ModKey.ToString(), $"{vint.IDString()}.json");
                    if (line.variants.Count > 0)
                    {
                        File.WriteAllText(jso, JsonConvert.SerializeObject(line.variants, settings));
                    }
                }
            }
            catch (Exception ex)
            {
                Log($"{ex.Message}", LogMode.NORMAL);
                break;
            }
        }
    }
    static LineTracker? ProcLine(string Name, FormKey FormKey)
    {
        var line = lines.GetOrAdd(Name, () => new()
        {
            forms = [FormKey],
            variants = [],
        });
        if (line.variants.Count > 0 && line.variants.All(x => x.reg_frags == null))
        {
            line.forms.Add(FormKey);
            Log($"Skipping {Name}", LogMode.NORMAL);
            return line;
        }
        //Basic Text Line
        if (!Name.Contains('<') && !Name.Contains('>') && !(Name.StartsWith('(') && Name.EndsWith(')')) && !(Name.StartsWith('[') && !Name.EndsWith(']')) && !(Name.EndsWith('*') && Name.StartsWith('*')) && !Name.Contains('_') && Name != "..." && !Name.StartsWith('$'))
        {
            var dat = Generate(Name);
            if (dat != null)
            {
                line.variants.Add(new()
                {
                    guid = dat.Value.guid,
                    splen = dat.Value.splen,
                    reg_frags = null,
                });
            }
        }
        //One of many different possible type variant data.
        else
        {
            if (Name != "...")
            {
                var vc = line.variants.Count;
                var cont = APIInfo.replacementLists.Where(x => Name.Contains($"<{x.Key}>")).ToDictionary();
                foreach (var (vd, tline) in cont.GenerateTemplatedCartesianProduct(Name))
                {
                    Log($"{tline}", LogMode.NORMAL);
                    if (!tline.Contains('<') && !tline.Contains('>') && !vd.All(x => line.variants.Any(y => y.reg_frags?.Contains(x) ?? false)))
                    {
                        var ld = Generate(tline);
                        if (ld != null)
                        {
                            line.variants.Add(new()
                            {
                                guid = ld.Value.guid,
                                splen = ld.Value.splen,
                                reg_frags = vd,
                            });
                        }
                    }
                }
            }
        }
        return line;
    }

    static void Log(string lt, LogMode md)
    {
        if (APIInfo.log_mode >= md)
        {
            Console.WriteLine(lt);
        }
    }
    static LineData? Generate(string text)
    {
        var guid = Guid.NewGuid().ToString().ToUpper();
        while (lines.Any(x => x.Value.variants.Any(x => x.guid == $"{guid}")) || File.Exists(Path.Join(EDFP, "VGOutput", "fuz", $"{guid}.fuz")))
        {
            Log("Regenerating identical guid", LogMode.DEBUG);
            guid = Guid.NewGuid().ToString().ToUpper();
        }
        var mp3name = Path.Join(mp3, $"{guid}.mp3");
        var wavname = Path.Join(wav, $"{guid}.wav");
        var rwavnam = Path.Join(wav, $"{guid}.resamp.wav");
        var lipname = Path.Join(lip, $"{guid}.lip");
        var xwmname = Path.Join(xwm, $"{guid}.xwm");
        var fuzname = Path.Join(fuz, $"{guid}.fuz");
        if (!File.Exists(mp3name) && !File.Exists(fuzname))
        {
            Log($"Generating: {text}", LogMode.NORMAL);
            StringContent stringContent = new(JsonConvert.SerializeObject(new Request(text, APIInfo)), Encoding.UTF8, "application/json");
            var cli = client.PostAsync($"/speak", stringContent);
            cli.Wait();
            if (cli.Result.IsSuccessStatusCode)
            {
                var file = File.OpenWrite(wavname);
                cli.Result.Content.CopyTo(file, null, CancellationToken.None);
                file.Close();
            }
            else
            {
                Log($"error: {cli.Result.StatusCode}", LogMode.NORMAL);
                throw new Exception(cli.Result.Content.ToString());
            }
        }
        if (!File.Exists(fuzname) && File.Exists(wavname))
        {

            var p = new ProcessStartInfo($"{EDFP}/ffmpeg.exe")
            {
                Arguments = $"-i \"{wavname}\" -ac 1 \"{mp3name}\"",
                RedirectStandardError = true,
                RedirectStandardInput = true,
                RedirectStandardOutput = true
            };
            var d = Process.Start(p);
            if (!d!.WaitForExit(20000)) d.Kill();
            LineData ret = new()
            {
                guid = guid,
                splen = Exts.GetMp3Duration(mp3name),
            };
            p.FileName = $"{EDFP}/FaceFXWrapper.exe";
            p.Arguments = $"Skyrim USEnglish FonixData.cdf \"{wavname}\" \"{rwavnam}\" \"{lipname}\" \"{text.Replace("\"", "\\\"")}\"";
            d = Process.Start(p);
            if (!d!.WaitForExit(20000)) d.Kill();
            p.FileName = $"{EDFP}/xWMAEncode.exe";
            p.Arguments = $"\"{wavname}\" \"{xwmname}\"";
            d = Process.Start(p);
            if (!d!.WaitForExit(20000)) d.Kill();
            p.FileName = $"{EDFP}/BmlFuzEncode.exe";
            p.Arguments = $"\"{fuzname}\" \"{xwmname}\" \"{lipname}\"";
            d = Process.Start(p);
            if (!d!.WaitForExit(20000)) d.Kill();
            Log($"Generated {text}", LogMode.NORMAL);
            return ret;
        }
        else
        {
            Log($"Skipping {text}", LogMode.NORMAL);
        }
        return null;
    }
}

public static partial class REG
{
    [GeneratedRegex("<([^=]*)=([^>]*)>")]
    private static partial Regex QuestAlias();
    public static Regex TextAliases => QuestAlias();
    [GeneratedRegex("(\\s?\\(.*\\)\\s?)")]
    private static partial Regex Hidden();
    public static Regex HiddenFN => Hidden();
    [GeneratedRegex("(\\s?\\[.*\\]\\s?)")]
    private static partial Regex Hidden2();
    public static Regex HiddenFN2 => Hidden2();
}
